name: Sonar Scanner
on: push

jobs:
  SonarQube:
    runs-on: self-hosted
    steps:
      - run: pwd
      - run: ls
      - run: git checkout main
      - run: git pull
      - run: ls
#      - run: sonar-scanner -Dsonar.token=${{ secrets.SONAR_TOKEN }}
      - run: echo "${{ secrets.SONAR_TOKEN }}"
