name: SonarQube forver
on:
  push:
    branches:
      - '*'

jobs:
  node-js-demo:
    runs-on: [self-hosted, linux, x64]
    steps:
      - run: pwd
      - run: ls
      - name: mog
        uses: actions/checkout@v2
      - run: pwd
      - run: ls
      - run: sonar-scanner 
