name: Sonar Scanner
on: push

jobs:
  SonarQube:
    runs-on: [self-hosted, linux, x64]
    steps:
      - run: pwd
      - run: ls
#      - run: sonar-scanner -Dsonar.token=${{ secrets.SONAR_TOKEN }}
#      - run: echo "${{ secrets.SONAR_TOKEN }}"
