name: SonarQube forver
on:
  push:
    branches:
      - '*'

jobs:
  sonar-gameplay:
    runs-on: [self-hosted, linux, x64]
    steps:
      - run: pwd
      - run: ls
      - name: mog
        uses: actions/checkout@v2
      - run: pwd
      - run: ls
      - run: sonar-scanner 
      - run: cd /home/icanio10096/icanio/Shell-Script/SonarQube
      - run: pwd
      - run: ./sonar-args.sh omg-sonar-omg
