name: SonarQube forver
on:
  push:
    branches:
      - '*'

jobs:
  sonar-gameplay:
    runs-on: [self-hosted, linux, x64]
    steps:
      - run: pwd
      - run: ls
      - name: mog
        uses: actions/checkout@v2
      - run: pwd
      - run: ls
      - run: sonar-scanner 
      - name: difficult
        run: |
         OMG=$(cd /home/icanio10096/icanio/Shell-Script/SonarQube ; ./sonar-args.sh omg-sonar-omg)
         if [ "$OMG" -eq "Success" ]
         then
            echo "Test Passed"
         else
            echo "Test Failed"
         fi
