name: Sonar Scanner
on: push

jobs:
  SonarQube:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '18'
      - run: npm install
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
